name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Start server in background
        run: |
          npm run dev &
          sleep 10 # Даем серверу время запуститься

      - name: Run API tests
        run: |
          chmod +x ./tests/test_api.sh
          ./tests/test_api.sh

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: |
            test-results.*
            logs/*.log
