name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_ENV: test
  JWT_SECRET: "your_ultra_secure_jwt_secret_key_change_this_in_production"
  DATABASE_URL: "postgres://test:test@postgres:5432/test"
  FRONTEND_URL: "http://localhost:3000"
  PORT: 5000

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl netcat-openbsd  # Changed to specific package
          npm ci

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            nc -z postgres 5432 && { echo "PostgreSQL is ready"; exit 0; }
            sleep 5
            echo "Waiting for PostgreSQL (attempt $i/10)..."
          done
          echo "PostgreSQL failed to start"
          exit 1

      - name: Start server
        run: |
          npm run dev > server.log 2>&1 &
          for i in {1..10}; do
            if curl -s http://localhost:$PORT/api/health >/dev/null; then
              echo "Server is ready"
              exit 0
            fi
            sleep 5
            echo "Waiting for server (attempt $i/10)..."
          done
          echo "Server failed to start"
          exit 1

      - name: Run API tests
        timeout-minutes: 5
        run: |
          chmod +x ./tests/test_api.sh
          export BASE_URL="http://localhost:$PORT"
          ./tests/test_api.sh | tee test-output.log
          if grep -q "ERROR" test-output.log; then
            echo "::error::Some tests failed"
            exit 1
          fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            server.log
            test-output.log
